#!/bin/bash

BIN="/usr/local/bin/askpass"; touch $BIN; chmod 755 $BIN
security add-generic-password -a $USER -s login -T "" -w
echo "#!/bin/sh\\nsecurity find-generic-password -a $USER -s login -w" > $BIN
echo "\\n# Set sudo helper.\\nexport SUDO_ASKPASS=$BIN" >> ~/.${SHELL##/*/}rc

/bin/bash -c "$(curl -fsSL 'https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh')"

brew install git
git -V

git clone https://github.com/dandude975/ChemicalDatabase

brew install mysql
mysql -V
brew services start mysql
brew install pyenv

pyenv install 3.10

python3 -m ensurepip
python3 -m pip install mysql-connector-python
Python3 ~/ChemicalDatabase/firstLaunch.py

SUDO_ASKPASS=/usr/X11R6/bin/ssh-askpass sudo -A rm ~/ChemicalDatabase/install
